version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: "api"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@broker:5672/"
      CELERY_RESULT_BACKEND: "rpc://"
    command: "poetry run uvicorn example.api:api --reload --host 0.0.0.0 --reload"

  backend:
    image: redis:latest
    hostname: backend
    container_name: "backend"

  broker:
    image: rabbitmq:management
    hostname: broker
    container_name: "broker"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: "celery_worker"
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@broker:5672/"
      CELERY_RESULT_BACKEND: "rpc://"
    command: "poetry run celery -A example.celery_worker.celery worker --loglevel=info"
    depends_on:
      - api
      - backend
      - broker
